language: node_js
node_js: 12
addons:
  code_climate:
    repo_token: CODE_CLIMATE_TOKEN
script: npm run test
before_script:
  - npm install
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info