name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2.3.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn build --if-present
    - run: yarn test

    - name: Codecov
      uses: codecov/codecov-action@v1.0.13

    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.7.3
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TOKEN }}
      with:
        coverageCommand: yarn test
